trigger:
- master

jobs:
- job: SourceCodeExtraction
  displayName: Extract and compress source code
  pool: Default
  steps:   

  - task: ArchiveFiles@2
    displayName: Extract source code to zip
    inputs:
      rootFolderOrFile: '$(Build.Repository.LocalPath)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/DbMocker-source-code.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: Artifact publication
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'DbMocker'
      publishLocation: 'Container'

- job: CompileSourceCode
  displayName: Compile source code
  pool: Default
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore Package
    inputs:
      command: 'restore'
      configuration: '$(BuildConfiguration)'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      
  - task: DotNetCoreCLI@2
    displayName: Build projects
    inputs:
      command: 'build'  
      configuration: '$(BuildConfiguration)' 
      projects: '**/*.csproj'
      packDirectory: '$(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Tests
    inputs:
      command: 'test'
      configuration: '$(BuildConfiguration)'
      projects: '**/*.Tests.csproj'
      testRunTitle: 'Tests'

  - task: DotNetCoreCLI@2
    displayName: Package creation
    inputs:
      command: 'pack'
      packagesToPack: 'DbMocker/DbMocker.csproj'
      configuration: '$(BuildConfiguration)'
      versioningScheme: 'off'

  - task: PublishBuildArtifacts@1
    displayName: Artifact publication
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'DbMocker'
      publishLocation: 'Container'

- job: PublishOnGitHub
  displayName: Publish artifact to GitHub
  pool: Default
  dependsOn: [
    SourceCodeExtraction,
    CompileSourceCode
  ]
  steps:
  - task: GitHubRelease@1
    displayName: Publish to GitHub
    inputs:
      gitHubConnection: 'GitHub'
      repositoryName: 'aclerbois-sandbox/DbMocker'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      title: 'DbMocker'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'My new version'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
